
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author lolog
 */
public class playwithfreind2 extends javax.swing.JFrame {

      Player player1 = new Player();
     Player player2 = new Player();
    
     
 
     
     public void getPlayersNames(){
        String name1 = JOptionPane.showInputDialog("please enter the name of the player 1:");
        String name2 = JOptionPane.showInputDialog("please enter the name of the player 2:");
         
        player1.setName(name1);
        player2.setName(name2);
         
        player1.setNumber(1);
        player1.setNumber(2);
     }
    
     
     public void getthebuttonclicked(){
         
        
         
         
         
     }
    
    
    


      
    /**
     * Creates new form playwithfreind2
     */
    public playwithfreind2() {
        initComponents();
        getPlayersNames();
       
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        bt1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        bt2 = new javax.swing.JButton();
        bt3 = new javax.swing.JButton();
        bt4 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        bt5 = new javax.swing.JButton();
        bt6 = new javax.swing.JButton();
        bt7 = new javax.swing.JButton();
        bt8 = new javax.swing.JButton();
        bt9 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        bt10 = new javax.swing.JButton();
        bt11 = new javax.swing.JButton();
        bt12 = new javax.swing.JButton();
        bt13 = new javax.swing.JButton();
        bt14 = new javax.swing.JButton();
        bt15 = new javax.swing.JButton();
        bt16 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));
        jPanel2.setLayout(new java.awt.GridLayout(4, 7));

        jLabel4.setToolTipText("");
        jPanel2.add(jLabel4);
        jPanel2.add(jLabel6);
        jPanel2.add(jLabel5);
        jPanel2.add(jLabel1);

        bt1.setBackground(new java.awt.Color(0, 0, 51));
        bt1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/nimgame/pic/rsz_matchstick-n43y6b8-600.jpg"))); // NOI18N
        bt1.setContentAreaFilled(false);
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });
        jPanel2.add(bt1);
        jPanel2.add(jLabel2);
        jPanel2.add(jLabel7);
        jPanel2.add(jLabel3);
        jPanel2.add(jLabel12);
        jPanel2.add(jLabel8);
        jPanel2.add(jLabel9);

        bt2.setBackground(new java.awt.Color(0, 0, 51));
        bt2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/nimgame/pic/rsz_matchstick-n43y6b8-600.jpg"))); // NOI18N
        bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt2ActionPerformed(evt);
            }
        });
        jPanel2.add(bt2);

        bt3.setBackground(new java.awt.Color(0, 0, 51));
        bt3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/nimgame/pic/rsz_matchstick-n43y6b8-600.jpg"))); // NOI18N
        bt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt3ActionPerformed(evt);
            }
        });
        jPanel2.add(bt3);

        bt4.setBackground(new java.awt.Color(0, 0, 51));
        bt4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/nimgame/pic/rsz_matchstick-n43y6b8-600.jpg"))); // NOI18N
        bt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt4ActionPerformed(evt);
            }
        });
        jPanel2.add(bt4);
        jPanel2.add(jLabel11);
        jPanel2.add(jLabel10);
        jPanel2.add(jLabel13);
        jPanel2.add(jLabel14);

        bt5.setBackground(new java.awt.Color(0, 0, 51));
        bt5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/nimgame/pic/rsz_matchstick-n43y6b8-600.jpg"))); // NOI18N
        bt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt5ActionPerformed(evt);
            }
        });
        jPanel2.add(bt5);

        bt6.setBackground(new java.awt.Color(0, 0, 51));
        bt6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/nimgame/pic/rsz_matchstick-n43y6b8-600.jpg"))); // NOI18N
        bt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt6ActionPerformed(evt);
            }
        });
        jPanel2.add(bt6);

        bt7.setBackground(new java.awt.Color(0, 0, 51));
        bt7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/nimgame/pic/rsz_matchstick-n43y6b8-600.jpg"))); // NOI18N
        bt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt7ActionPerformed(evt);
            }
        });
        jPanel2.add(bt7);

        bt8.setBackground(new java.awt.Color(0, 0, 51));
        bt8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/nimgame/pic/rsz_matchstick-n43y6b8-600.jpg"))); // NOI18N
        bt8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt8ActionPerformed(evt);
            }
        });
        jPanel2.add(bt8);

        bt9.setBackground(new java.awt.Color(0, 0, 51));
        bt9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/nimgame/pic/rsz_matchstick-n43y6b8-600.jpg"))); // NOI18N
        bt9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt9ActionPerformed(evt);
            }
        });
        jPanel2.add(bt9);
        jPanel2.add(jLabel15);
        jPanel2.add(jLabel16);

        bt10.setBackground(new java.awt.Color(0, 0, 51));
        bt10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/nimgame/pic/rsz_matchstick-n43y6b8-600.jpg"))); // NOI18N
        bt10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt10ActionPerformed(evt);
            }
        });
        jPanel2.add(bt10);

        bt11.setBackground(new java.awt.Color(0, 0, 51));
        bt11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/nimgame/pic/rsz_matchstick-n43y6b8-600.jpg"))); // NOI18N
        bt11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt11ActionPerformed(evt);
            }
        });
        jPanel2.add(bt11);

        bt12.setBackground(new java.awt.Color(0, 0, 51));
        bt12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/nimgame/pic/rsz_matchstick-n43y6b8-600.jpg"))); // NOI18N
        bt12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt12ActionPerformed(evt);
            }
        });
        jPanel2.add(bt12);

        bt13.setBackground(new java.awt.Color(0, 0, 51));
        bt13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/nimgame/pic/rsz_matchstick-n43y6b8-600.jpg"))); // NOI18N
        bt13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt13ActionPerformed(evt);
            }
        });
        jPanel2.add(bt13);

        bt14.setBackground(new java.awt.Color(0, 0, 51));
        bt14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/nimgame/pic/rsz_matchstick-n43y6b8-600.jpg"))); // NOI18N
        bt14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt14ActionPerformed(evt);
            }
        });
        jPanel2.add(bt14);

        bt15.setBackground(new java.awt.Color(0, 0, 51));
        bt15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/nimgame/pic/rsz_matchstick-n43y6b8-600.jpg"))); // NOI18N
        bt15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt15ActionPerformed(evt);
            }
        });
        jPanel2.add(bt15);

        bt16.setBackground(new java.awt.Color(0, 0, 51));
        bt16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/nimgame/pic/rsz_matchstick-n43y6b8-600.jpg"))); // NOI18N
        bt16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt16ActionPerformed(evt);
            }
        });
        jPanel2.add(bt16);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(130, 140, 300, 360);

        jButton18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton18.setForeground(new java.awt.Color(0, 0, 51));
        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/nimgame/pic/rsz_images.png"))); // NOI18N
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton18);
        jButton18.setBounds(40, 40, 70, 50);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("NIM'S GAME ");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(180, 20, 440, 80);

        jButton19.setForeground(new java.awt.Color(0, 0, 51));
        jButton19.setText("Friend Turn's");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton19);
        jButton19.setBounds(470, 340, 120, 23);

        jButton20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton20.setForeground(new java.awt.Color(0, 0, 51));
        jButton20.setText("EXIT");
        jPanel1.add(jButton20);
        jButton20.setBounds(510, 470, 72, 27);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt3ActionPerformed

    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt2ActionPerformed

    private void bt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt7ActionPerformed

    private void bt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt4ActionPerformed

    private void bt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt8ActionPerformed

    private void bt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt6ActionPerformed

    private void bt9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt9ActionPerformed

    private void bt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt5ActionPerformed

    private void bt15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt15ActionPerformed

    private void bt16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt16ActionPerformed

    private void bt14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt14ActionPerformed

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt1ActionPerformed

    private void bt10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt10ActionPerformed

    private void bt11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt11ActionPerformed

    private void bt12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt12ActionPerformed

    private void bt13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt13ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed

        MainPage m = new MainPage();
        m.setVisible(true);    
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton19ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(playwithfreind2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(playwithfreind2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(playwithfreind2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(playwithfreind2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new playwithfreind2().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt10;
    private javax.swing.JButton bt11;
    private javax.swing.JButton bt12;
    private javax.swing.JButton bt13;
    private javax.swing.JButton bt14;
    private javax.swing.JButton bt15;
    private javax.swing.JButton bt16;
    private javax.swing.JButton bt2;
    private javax.swing.JButton bt3;
    private javax.swing.JButton bt4;
    private javax.swing.JButton bt5;
    private javax.swing.JButton bt6;
    private javax.swing.JButton bt7;
    private javax.swing.JButton bt8;
    private javax.swing.JButton bt9;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
