/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author lolog
 */
public class PlayWithPC extends javax.swing.JFrame {

    /**
     * Creates new form PlayWithPC
     */
    public PlayWithPC() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton18 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton19 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setLayout(null);

        jButton18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton18.setForeground(new java.awt.Color(0, 0, 51));
        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/nimgame/pic/rsz_images.png"))); // NOI18N
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton18);
        jButton18.setBounds(40, 40, 70, 50);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NIM'S GAME ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(180, 20, 440, 80);

        jButton19.setForeground(new java.awt.Color(0, 0, 51));
        jButton19.setText("PC Turn's");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton19);
        jButton19.setBounds(490, 250, 120, 23);

        jButton17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton17.setForeground(new java.awt.Color(0, 0, 51));
        jButton17.setText("EXIT");
        jPanel1.add(jButton17);
        jButton17.setBounds(520, 400, 72, 27);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/nimgame/pic/rsz_matchstick-n43y6b8-600.jpg"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(300, 120, 20, 70);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/nimgame/pic/rsz_matchstick-n43y6b8-600.jpg"))); // NOI18N
        jPanel1.add(jButton7);
        jButton7.setBounds(260, 200, 20, 70);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/nimgame/pic/rsz_matchstick-n43y6b8-600.jpg"))); // NOI18N
        jPanel1.add(jButton3);
        jButton3.setBounds(300, 200, 20, 70);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/nimgame/pic/rsz_matchstick-n43y6b8-600.jpg"))); // NOI18N
        jPanel1.add(jButton6);
        jButton6.setBounds(340, 200, 20, 70);

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/nimgame/pic/rsz_matchstick-n43y6b8-600.jpg"))); // NOI18N
        jPanel1.add(jButton11);
        jButton11.setBounds(220, 280, 20, 70);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/nimgame/pic/rsz_matchstick-n43y6b8-600.jpg"))); // NOI18N
        jPanel1.add(jButton9);
        jButton9.setBounds(260, 280, 20, 70);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/nimgame/pic/rsz_matchstick-n43y6b8-600.jpg"))); // NOI18N
        jPanel1.add(jButton4);
        jButton4.setBounds(300, 280, 20, 70);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/nimgame/pic/rsz_matchstick-n43y6b8-600.jpg"))); // NOI18N
        jPanel1.add(jButton8);
        jButton8.setBounds(340, 280, 20, 70);

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/nimgame/pic/rsz_matchstick-n43y6b8-600.jpg"))); // NOI18N
        jPanel1.add(jButton10);
        jButton10.setBounds(380, 280, 20, 70);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/nimgame/pic/rsz_matchstick-n43y6b8-600.jpg"))); // NOI18N
        jPanel1.add(jButton1);
        jButton1.setBounds(420, 360, 20, 70);

        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/nimgame/pic/rsz_matchstick-n43y6b8-600.jpg"))); // NOI18N
        jPanel1.add(jButton14);
        jButton14.setBounds(380, 360, 20, 70);

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/nimgame/pic/rsz_matchstick-n43y6b8-600.jpg"))); // NOI18N
        jPanel1.add(jButton12);
        jButton12.setBounds(340, 360, 20, 70);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/nimgame/pic/rsz_matchstick-n43y6b8-600.jpg"))); // NOI18N
        jPanel1.add(jButton5);
        jButton5.setBounds(300, 360, 20, 70);

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/nimgame/pic/rsz_matchstick-n43y6b8-600.jpg"))); // NOI18N
        jPanel1.add(jButton13);
        jButton13.setBounds(260, 360, 20, 70);

        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/nimgame/pic/rsz_matchstick-n43y6b8-600.jpg"))); // NOI18N
        jPanel1.add(jButton15);
        jButton15.setBounds(220, 360, 20, 70);

        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/nimgame/pic/rsz_matchstick-n43y6b8-600.jpg"))); // NOI18N
        jPanel1.add(jButton16);
        jButton16.setBounds(180, 360, 20, 70);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 699, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed

        MainPage m = new MainPage();
        m.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlayWithPC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlayWithPC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlayWithPC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlayWithPC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlayWithPC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
